version: "3.7"

services:
  facerecognition-cpu:
    build:
      dockerfile: Dockerfile.face-cpu
      context: .
    depends_on:
      - openvino
    environment:
      DISPLAY: ':0'
    volumes:
      - /dev:/dev:shared
      - /tmp/.X11-unix:/tmp/.X11-unix 
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.usb-camera == true
    privileged: true
